// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muknolzoifqslptxxoxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11a25vbHpvaWZxc2xwdHh4b3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzQyMzUsImV4cCI6MjA2MjA1MDIzNX0.3HLpaRIVu1h1jqBFUKxuXb6DC4BREUqjr12swJXOO_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);